/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class midicore_NativeMidiDeviceEventListener */

#ifndef _Included_midicore_NativeMidiDeviceEventListener
#define _Included_midicore_NativeMidiDeviceEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     midicore_NativeMidiDeviceEventListener
 * Method:    onAttached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_midicore_NativeMidiDeviceEventListener_onAttached
  (JNIEnv *, jobject);

/*
 * Class:     midicore_NativeMidiDeviceEventListener
 * Method:    onDetached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_midicore_NativeMidiDeviceEventListener_onDetached
  (JNIEnv *, jobject);

/*
 * Class:     midicore_NativeMidiDeviceEventListener
 * Method:    onMidiData
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_midicore_NativeMidiDeviceEventListener_onMidiData
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
